version: "1.0"
info:
  model: int-scaffold
packages:
- name: Test17FebProject
  gitServerName: rath
  gitUrl: https://github.com/Rashmi-Thakare-IBM
  gitUsername: Rashmi-Thakare-IBM
  gitBranch: main
- name: WmSalesforceProvider
  version: 10.7.0.0.53
services:
- serviceName: project.test17feb.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.connections:tytyty24feb
  packages:
  - name: Test17FebProject
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.53
- serviceName: project.test17feb.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.operations.actions:action_21feb
  packages:
  - name: Test17FebProject
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.53
- serviceName: project.test17feb.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.operations.actions:customdelete
  packages:
  - name: Test17FebProject
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.53
- serviceName: project.test17feb.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.operations.actions:rrrrrr
  packages:
  - name: Test17FebProject
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.53
- serviceName: project.test17feb.integrations:custom17Feb
  packages:
  - name: Test17FebProject
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.53
- serviceName: project.test17feb.integrations:lakr_21feb
  packages:
  - name: Test17FebProject
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.53
- serviceName: project.test17feb.integrations:qqqq
  packages:
  - name: Test17FebProject
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.53
- serviceName: project.test17feb.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.operations.actions:rash19feb
  packages:
  - name: Test17FebProject
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.53
- serviceName: project.test17feb.integrations:test17Febu
  packages:
  - name: Test17FebProject
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.53
configurationVariables:
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:tytyty24feb.cr.username
  : rithi@softwareag.com
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:tytyty24feb.startupBackoffSecs
  : "10"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:tytyty24feb.cn.sockBuffSize
  : "8192"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:tytyty24feb.cn.retryCount
  : "3"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:tytyty24feb.cr.authSchemeType
  : basic
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:tytyty24feb.rh.requestHeaderNames
  : "Content-Type,SOAPAction"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:tytyty24feb.expireTimeout
  : "1000"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:tytyty24feb.pr.serverRedirectMax
  : "5"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:tytyty24feb.cn.socketStaleCheck
  : "true"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:tytyty24feb.cr.preemptiveAuthEnabled
  : "false"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:tytyty24feb.rh.requestHeaderValues
  : "text/xml,login"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:tytyty24feb.cn.enableCompression
  : "false"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:tytyty24feb.pr.userAgent
  : Cloudstreams
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:tytyty24feb.cn.idleTimeout
  : "-1"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:tytyty24feb.connectionEnabled
  : "true"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:tytyty24feb.pr.useChunking
  : "false"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:tytyty24feb.poolable
  : "true"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:tytyty24feb.maximumPoolSize
  : "10"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:tytyty24feb.timeoutType
  : fixed
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:tytyty24feb.startupRetryCount
  : "0"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:tytyty24feb.cn.enableSNI
  : "true"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:tytyty24feb.cn.validateAfterInactivity
  : "1000"
  ? iscloudstreamsconnectorservice.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..operations..actions:customdelete.virtualServiceName
  : WmCloudStreams.SoapVS
  ? iscloudstreamsconnectorservice.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..operations..actions:rrrrrr.connectionAlias
  : project.test17feb.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.connections:rashmi17feb
  ? iscloudstreamsconnectorservice.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..operations..actions:action_21feb.connectionAlias
  : project.test17feb.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.connections:tytyty24feb
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:tytyty24feb.cn.reuseAddr
  : "false"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:tytyty24feb.cr.password
  : "{AES}OYSjbNfOLUKJAT+MWJt0w3FPbUooYAcCzhGF0UMKgsfxDQ1MMLJvU+e5tmiaXP+/"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:tytyty24feb.sessionExpiry
  : "14"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:tytyty24feb.cn.providerUrl
  : https://login.salesforce.com/services/Soap/u/53.0
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:tytyty24feb.pr.followServerRedirects
  : "true"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:tytyty24feb.cn.readTimeout
  : "180000"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:tytyty24feb.blockTimeout
  : "1000"
  ? iscloudstreamsconnectorservice.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..operations..actions:customdelete.connectionAlias
  : project.test17feb.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.connections:rath17Feb
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:tytyty24feb.cn.tcpNoDelay
  : "false"
  ? iscloudstreamsconnectorservice.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..operations..actions:action_21feb.virtualServiceName
  : WmCloudStreams.SoapVS
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:tytyty24feb.cn.connectTimeout
  : "180000"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:tytyty24feb.cn.retryIfRequestSentOk
  : "true"
  ? iscloudstreamsconnectorservice.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..operations..actions:rrrrrr.virtualServiceName
  : WmCloudStreams.SoapVS
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:tytyty24feb.pr.allowCircularRedirects
  : "true"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:tytyty24feb.minimumPoolSize
  : "1"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:tytyty24feb.poolIncrementSize
  : "1"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:tytyty24feb.pr.protocolVersion
  : HTTP/1.1
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:tytyty24feb.cn.socketLinger
  : "-1"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:tytyty24feb.cn.hostnameVerifier
  : org.apache.http.conn.ssl.DefaultHostnameVerifier
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:tytyty24feb.cn.keepAliveInterval
  : "300000"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:tytyty24feb.pr.useExpectCont
  : "false"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:tytyty24feb.pr.httpContentCharSet
  : ISO-8859-1
