version: "1.0"
info:
  model: int-scaffold
packages:
- name: Test17FebProject
  gitServerName: rath
  gitUrl: https://github.com/Rashmi-Thakare-IBM
  gitUsername: Rashmi-Thakare-IBM
  gitBranch: main
- name: WmSalesforceProvider
  version: 10.7.0.0.53
services:
- serviceName: project.test17feb.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.connections:lakr_21feb
  packages:
  - name: Test17FebProject
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.53
- serviceName: project.test17feb.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.operations.actions:customdelete
  packages:
  - name: Test17FebProject
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.53
- serviceName: project.test17feb.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.operations.actions:rrrrrr
  packages:
  - name: Test17FebProject
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.53
- serviceName: project.test17feb.integrations:custom17Feb
  packages:
  - name: Test17FebProject
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.53
- serviceName: project.test17feb.integrations:lakr_21feb
  packages:
  - name: Test17FebProject
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.53
- serviceName: project.test17feb.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.operations.actions:action_21feb
  packages:
  - name: Test17FebProject
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.53
- serviceName: project.test17feb.integrations:qqqq
  packages:
  - name: Test17FebProject
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.53
- serviceName: project.test17feb.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.operations.actions:rash19feb
  packages:
  - name: Test17FebProject
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.53
- serviceName: project.test17feb.integrations:test17Febu
  packages:
  - name: Test17FebProject
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.53
configurationVariables:
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:lakr_21feb.pr.httpContentCharSet
  : ISO-8859-1
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:lakr_21feb.connectionEnabled
  : "true"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:lakr_21feb.pr.userAgent
  : Cloudstreams
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:lakr_21feb.cn.enableSNI
  : "true"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:lakr_21feb.poolIncrementSize
  : "1"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:lakr_21feb.startupBackoffSecs
  : "10"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:lakr_21feb.expireTimeout
  : "1000"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:lakr_21feb.cr.authSchemeType
  : none
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:lakr_21feb.minimumPoolSize
  : "1"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:lakr_21feb.pr.useChunking
  : "false"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:lakr_21feb.cn.validateAfterInactivity
  : "1000"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:lakr_21feb.sessionExpiry
  : "14"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:lakr_21feb.cn.retryIfRequestSentOk
  : "true"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:lakr_21feb.cn.socketStaleCheck
  : "true"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:lakr_21feb.cn.socketLinger
  : "-1"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:lakr_21feb.cn.retryCount
  : "3"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:lakr_21feb.startupRetryCount
  : "0"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:lakr_21feb.cn.tcpNoDelay
  : "false"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:lakr_21feb.cr.preemptiveAuthEnabled
  : "false"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:lakr_21feb.cn.idleTimeout
  : "-1"
  ? iscloudstreamsconnectorservice.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..operations..actions:customdelete.virtualServiceName
  : WmCloudStreams.SoapVS
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:lakr_21feb.pr.serverRedirectMax
  : "5"
  ? iscloudstreamsconnectorservice.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..operations..actions:rrrrrr.connectionAlias
  : project.test17feb.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.connections:rashmi17feb
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:lakr_21feb.blockTimeout
  : "1000"
  ? iscloudstreamsconnectorservice.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..operations..actions:action_21feb.connectionAlias
  : project.test17feb.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.connections:lakr_21feb
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:lakr_21feb.pr.followServerRedirects
  : "true"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:lakr_21feb.cn.enableCompression
  : "false"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:lakr_21feb.cn.providerUrl
  : https://login.salesforce.com/services/Soap/u/53.0
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:lakr_21feb.rh.requestHeaderNames
  : "Content-Type,SOAPAction"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:lakr_21feb.cn.sockBuffSize
  : "8192"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:lakr_21feb.pr.useExpectCont
  : "false"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:lakr_21feb.cn.connectTimeout
  : "180000"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:lakr_21feb.cn.readTimeout
  : "180000"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:lakr_21feb.cr.username
  : rgud@softwareag.com
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:lakr_21feb.maximumPoolSize
  : "10"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:lakr_21feb.pr.protocolVersion
  : HTTP/1.1
  ? iscloudstreamsconnectorservice.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..operations..actions:customdelete.connectionAlias
  : project.test17feb.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.connections:rath17Feb
  ? iscloudstreamsconnectorservice.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..operations..actions:action_21feb.virtualServiceName
  : WmCloudStreams.SoapVS
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:lakr_21feb.cn.keepAliveInterval
  : "300000"
  ? iscloudstreamsconnectorservice.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..operations..actions:rrrrrr.virtualServiceName
  : WmCloudStreams.SoapVS
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:lakr_21feb.pr.allowCircularRedirects
  : "true"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:lakr_21feb.timeoutType
  : fixed
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:lakr_21feb.cn.hostnameVerifier
  : org.apache.http.conn.ssl.DefaultHostnameVerifier
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:lakr_21feb.cr.password
  : "{AES}QwEMw5KuzYE8u5+I+ff4X9rfhEqHS37ppPhQzv9VSnOKpzcEVjOJ5WZM0h5XYAv/"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:lakr_21feb.rh.requestHeaderValues
  : "text/xml,login"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:lakr_21feb.cn.reuseAddr
  : "false"
  ? cloudstreamsconnection.project..test17feb..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:lakr_21feb.poolable
  : "true"
